---
# tasks for base_amq
- name: Set variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"
  tags: always

- name: Define desired state
  ansible.builtin.include_tasks: "{{ desired_state }}.yml"

- name: "Configure {{ ansible_os_family }}"
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"
  tags: always

...
