---
- name: Create group for AMQ
  become: true
  when:
    - desired_state == 'present'
    - amq_group is defined
  group:
    name: "{{ amq_group }}"
    gid: "{{ amq_gid | default(omit, true) }}"
    state: present

- name: Manage user for AMQ
  become: true
  user:
    name: "{{ amq_user }}"
    group: "{{ amq_group }}"
    uid: "{{ amq_uid | default( omit, true) }}"
    createhome: false
    state: "{{ desired_state }}"
    system: true

- name: Remove group for AMQ
  become: true
  when:
    - desired_state == 'absent'
    - amq_group is defined
  group:
    name: "{{ amq_group }}"
    gid: "{{ amq_gid | default(omit, true) }}"
    state: absent

- name: Manage directories
  become: true
  file:
    path: "{{ item }}"
    state: "{{ amq_dir_state }}"
    mode: 0755
    owner: "{{ amq_user }}"
    group: "{{ amq_group }}"
  loop:
    - "{{ amq_download_path }}"
    - "{{ amq_logdir }}"

- name: Install unzip
  package:
    name: unzip
    state: present

- name: Download Artemis
  when: desired_state == 'present'
  get_url:
    url: "{{ amq_download_url }}"
    checksum: "{{ amq_checksum }}"
    dest: "{{ amq_download_path }}/{{ amq_download_file }}"
    mode: 0644

- name: Extract archive
  become: true
  when: desired_state == 'present'
  unarchive:
    src: "{{ amq_download_path }}/{{ amq_download_file }}"
    dest: "{{ amq_install_dir }}"
    remote_src: true
    owner: "{{ amq_user }}"
    group: "{{ amq_group }}"
    creates: "{{ amq_home }}/bin/artemis"

- name: Create symlink
  become: true
  when: desired_state == 'present'
  file:
    src: "{{ amq_install_dir }}/apache-artemis-{{ amq_ver }}"
    dest: "{{ amq_home }}"
    state: link
    owner: "{{ amq_user }}"
    group: "{{ amq_group }}"
    mode: 0755

- name: Remove symlink
  become: true
  when: desired_state == 'absent'
  file:
    path: "{{ amq_home }}"
    state: absent
...
