---
dependency:
  name: galaxy
  requirements_file: requirements.yml
driver:
  name: docker
platforms:
  - name: base_amq
    image: dokken/almalinux-8
    pre_build_image: true
    command: /sbin/init
    privileged: true
    cgroupns_mode: host
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      callbacks_enabled: profile_tasks, timer
      become_method: machinectl
      executable: /bin/bash
      remote_tmp: /tmp/.ansible
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
    side_effect: ../resources/playbooks/side-effect.yml
verifier:
  name: ansible
...
