---
dependency:
  name: galaxy
  requirements_file: requirements.yml
driver:
  name: delegated
  options:
    managed: false
    login_cmd_template: 'ssh@{instance}'
platforms:
  - name: test-amq
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8 --max-line-length=120
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      executable: /bin/bash
  playbooks:
    converge: ../resources/playbooks/converge.yml
    cleanup: ../resources/playbooks/cleanup.yml
verifier:
  name: ansible
  directory: ../resources/playbooks
...
